dataset:
  batch_size: 20
  max_tokens: 4096
  samples_per_class: 10000
  num_chat: 1
train:
  max_length: 128
  output: './results'
  eval_strategy: "epoch"
  save_strategy: "no"
  batch_size: 8
  epochs: 10
  learning_rate: 0.0001
  weight_decay: 0.01
  num_workers: 1